sudo: required

services:
  - docker

install:
  - docker pull yowct/fuzzy-tribble || true
  - docker build --cache-from yowct/fuzzy-tribble --tag yowct/fuzzy-tribble .

script:
  - docker run yowct/fuzzy-tribble script/run_tests.sh
  - docker run yowct/fuzzy-tribble pylint src tests
  - docker run yowct/fuzzy-tribble mypy src tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push yowct/fuzzy-tribble;
    fi
