language: python
python:
  - "3.6"
install:
  - pip install setuptools==36.5.0
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest tests
  - pylint src tests
  - mypy src tests
